
.PHONY: all
all:  task1 task2 task3 task4

task1: main2_1.c
	gcc -o main2_1 main2_1.c

task2: main2_2.c
	gcc -o main2_2 main2_2.c

task3: main2_3.c
	gcc -o main2_3 main2_3.c

task4: main2_4.c
	gcc -o main2_4 main2_4.c

.PHONY: clean
clean:
	-rm  -f *.o main2_1 main2_2 main2_3 main2_4
